name: delivery_boy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^3.0.1
  animated_splash_screen: ^1.2.0
  flutter_html: ^2.2.1
  dotted_line: ^3.1.0
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.1
  shared_preferences: ^2.0.15
  flutter_dialogs: ^2.2.0
  awesome_dropdown: ^0.0.4
  otp_text_field: ^1.1.1
  pin_code_fields: ^7.4.0
  firebase_auth: ^3.3.19
  connectivity: ^3.0.3
  fluttertoast: ^8.0.9
  firebase_core: ^1.7.0
flutter:

  uses-material-design: true

  assets:
     - image/

#  fonts:
#    - family: Raleway
#      fonts:
#       - asset: fonts/Raleway-Regular.ttf
#       - asset: fonts/Raleway-Italic.ttf
#    - family: Roboto
#      fonts:
#       - asset: fonts/RobotoMono-Regular.ttf
#       - asset: fonts/RobotoMono-Bold.ttf

